services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - CORS_ORIGIN=http://localhost:5173
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.svelte-kit
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - PORT=5173
    depends_on:
      - backend
    restart: unless-stopped