services:
  # Backend Service
  - type: web
    name: chemreactions-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    buildCommand: docker build -t chemreactions-backend ./backend
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CORS_ORIGIN
        value: "https://chemreactions.org,https://chemistryreactionsfrontend.onrender.com"
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        fromDatabase:
          name: chemreactions-db
          property: connectionString
    healthCheckPath: /health

  # Frontend Service
  - type: web
    name: chemreactions-frontend
    env: docker
    dockerfilePath: frontend/Dockerfile
    envVars:
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: VITE_API_URL
        fromService:
          name: chemreactions-backend
          type: web
          property: url
    healthCheckPath: /

# Add a free PostgreSQL database if needed
databases:
  - name: chemreactions-db
    databaseName: chemreactions
    plan: free
    ipAllowList: [] # Allow all IPs