test_elements = [
    {
        "atomic_number": 1,
        "symbol": "H",
        "name": "Hydrogen",
        "group": "1",
        "period": 1,
        "block": "s-block",
        "atomic_weight": 1.008,
        "density": 0.00008988,
        "melting_point": 14.01,
        "boiling_point": 20.28,
        "specific_heat": 14.304,
        "electronegativity": 2.20,
        "abundance": 1400,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 2,
        "symbol": "He",
        "name": "Helium",
        "group": "18",
        "period": 1,
        "block": "s-block",
        "atomic_weight": 4.0026,
        "density": 0.0001785,
        "melting_point": None,
        "boiling_point": 4.22,
        "specific_heat": 5.193,
        "electronegativity": None,
        "abundance": 0.008,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 3,
        "symbol": "Li",
        "name": "Lithium",
        "group": "1",
        "period": 2,
        "block": "s-block",
        "atomic_weight": 6.94,
        "density": 0.534,
        "melting_point": 453.69,
        "boiling_point": 1560,
        "specific_heat": 3.582,
        "electronegativity": 0.98,
        "abundance": 20,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 4,
        "symbol": "Be",
        "name": "Beryllium",
        "group": "2",
        "period": 2,
        "block": "s-block",
        "atomic_weight": 9.0122,
        "density": 1.85,
        "melting_point": 1560,
        "boiling_point": 2742,
        "specific_heat": 1.825,
        "electronegativity": 1.57,
        "abundance": 2.8,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 5,
        "symbol": "B",
        "name": "Boron",
        "group": "13",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 10.81,
        "density": 2.34,
        "melting_point": 2349,
        "boiling_point": 4200,
        "specific_heat": 1.026,
        "electronegativity": 2.04,
        "abundance": 10,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 6,
        "symbol": "C",
        "name": "Carbon",
        "group": "14",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 12.011,
        "density": 2.267,
        "melting_point": 4000,
        "boiling_point": 4300,
        "specific_heat": 0.709,
        "electronegativity": 2.55,
        "abundance": 200,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 7,
        "symbol": "N",
        "name": "Nitrogen",
        "group": "15",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 14.007,
        "density": 0.0012506,
        "melting_point": 63.15,
        "boiling_point": 77.36,
        "specific_heat": 1.04,
        "electronegativity": 3.04,
        "abundance": 19,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 8,
        "symbol": "O",
        "name": "Oxygen",
        "group": "16",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 15.999,
        "density": 0.001429,
        "melting_point": 54.36,
        "boiling_point": 90.20,
        "specific_heat": 0.918,
        "electronegativity": 3.44,
        "abundance": 461000,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 9,
        "symbol": "F",
        "name": "Fluorine",
        "group": "17",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 18.998,
        "density": 0.001696,
        "melting_point": 53.53,
        "boiling_point": 85.03,
        "specific_heat": 0.824,
        "electronegativity": 3.98,
        "abundance": 585,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 10,
        "symbol": "Ne",
        "name": "Neon",
        "group": "18",
        "period": 2,
        "block": "p-block",
        "atomic_weight": 20.180,
        "density": 0.0009002,
        "melting_point": 24.56,
        "boiling_point": 27.07,
        "specific_heat": 1.03,
        "electronegativity": None,
        "abundance": 0.005,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 11,
        "symbol": "Na",
        "name": "Sodium",
        "group": "1",
        "period": 3,
        "block": "s-block",
        "atomic_weight": 22.990,
        "density": 0.968,
        "melting_point": 370.87,
        "boiling_point": 1156,
        "specific_heat": 1.228,
        "electronegativity": 0.93,
        "abundance": 23600,
        "origin": "primordial", 
        "phase": "solid"
    },
    {
        "atomic_number": 12,
        "symbol": "Mg",
        "name": "Magnesium",
        "group": "2",
        "period": 3,
        "block": "s-block",
        "atomic_weight": 24.305,
        "density": 1.738,
        "melting_point": 923,
        "boiling_point": 1363,
        "specific_heat": 1.023,
        "electronegativity": 1.31,
        "abundance": 23300,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 13,
        "symbol": "Al",
        "name": "Aluminium",
        "group": "13",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 26.982,
        "density": 2.70,
        "melting_point": 933.47,
        "boiling_point": 2792,
        "specific_heat": 0.897,
        "electronegativity": 1.61,
        "abundance": 82300,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 14,
        "symbol": "Si",
        "name": "Silicon",
        "group": "14",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 28.085,
        "density": 2.3290,
        "melting_point": 1687,
        "boiling_point": 3538,
        "specific_heat": 0.705,
        "electronegativity": 1.90,
        "abundance": 282000,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 15,
        "symbol": "P",
        "name": "Phosphorus",
        "group": "15",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 30.974,
        "density": 1.823,
        "melting_point": 317.30,
        "boiling_point": 550,
        "specific_heat": 0.769,
        "electronegativity": 2.19,
        "abundance": 1050,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 16,
        "symbol": "S",
        "name": "Sulfur",
        "group": "16",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 32.06,
        "density": 2.07,
        "melting_point": 388.36,
        "boiling_point": 717.87,
        "specific_heat": 0.71,
        "electronegativity": 2.58,
        "abundance": 350,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 17,
        "symbol": "Cl",
        "name": "Chlorine",
        "group": "17",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 35.45,
        "density": 0.0032,
        "melting_point": 171.6,
        "boiling_point": 239.11,
        "specific_heat": 0.479,
        "electronegativity": 3.16,
        "abundance": 145,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 18,
        "symbol": "Ar",
        "name": "Argon",
        "group": "18",
        "period": 3,
        "block": "p-block",
        "atomic_weight": 39.95,
        "density": 0.001784,
        "melting_point": 83.80,
        "boiling_point": 87.30,
        "specific_heat": 0.52,
        "electronegativity": None,
        "abundance": 3.5,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 19,
        "symbol": "K",
        "name": "Potassium",
        "group": "1",
        "period": 4,
        "block": "s-block",
        "atomic_weight": 39.098,
        "density": 0.89,
        "melting_point": 336.53,
        "boiling_point": 1032,
        "specific_heat": 0.757,
        "electronegativity": 0.82,
        "abundance": 20900,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 20,
        "symbol": "Ca",
        "name": "Calcium",
        "group": "2",
        "period": 4,
        "block": "s-block",
        "atomic_weight": 40.078,
        "density": 1.55,
        "melting_point": 1115,
        "boiling_point": 1757,
        "specific_heat": 0.647,
        "electronegativity": 1.00,
        "abundance": 41500,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 21,
        "symbol": "Sc",
        "name": "Scandium",
        "group": "3",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 44.956,
        "density": 2.985,
        "melting_point": 1814,
        "boiling_point": 3109,
        "specific_heat": 0.568,
        "electronegativity": 1.36,
        "abundance": 22,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 22,
        "symbol": "Ti",
        "name": "Titanium", 
        "group": "4",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 47.867,
        "density": 4.506,
        "melting_point": 1941,
        "boiling_point": 3560,
        "specific_heat": 0.523,
        "electronegativity": 1.54,
        "abundance": 5650,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 23,
        "symbol": "V",
        "name": "Vanadium",
        "group": "5",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 50.942,
        "density": 6.11,
        "melting_point": 2183,
        "boiling_point": 3680,
        "specific_heat": 0.489,
        "electronegativity": 1.63,
        "abundance": 120,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 24,
        "symbol": "Cr",
        "name": "Chromium",
        "group": "6",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 51.996,
        "density": 7.15,
        "melting_point": 2180,
        "boiling_point": 2944,
        "specific_heat": 0.449,
        "electronegativity": 1.66,
        "abundance": 102,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 25,
        "symbol": "Mn",
        "name": "Manganese",
        "group": "7",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 54.938,
        "density": 7.21,
        "melting_point": 1519,
        "boiling_point": 2334,
        "specific_heat": 0.479,
        "electronegativity": 1.55,
        "abundance": 950,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 26,
        "symbol": "Fe",
        "name": "Iron",
        "group": "8",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 55.845,
        "density": 7.874,
        "melting_point": 1811,
        "boiling_point": 3134,
        "specific_heat": 0.449,
        "electronegativity": 1.83,
        "abundance": 56300,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 27,
        "symbol": "Co",
        "name": "Cobalt",
        "group": "9",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 58.933,
        "density": 8.90,
        "melting_point": 1768,
        "boiling_point": 3200,
        "specific_heat": 0.421,
        "electronegativity": 1.88,
        "abundance": 25,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 28,
        "symbol": "Ni",
        "name": "Nickel",
        "group": "10",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 58.693,
        "density": 8.908,
        "melting_point": 1728,
        "boiling_point": 3186,
        "specific_heat": 0.444,
        "electronegativity": 1.91,
        "abundance": 84,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 29,
        "symbol": "Cu",
        "name": "Copper",
        "group": "11",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 63.546,
        "density": 8.96,
        "melting_point": 1357.77,
        "boiling_point": 2835,
        "specific_heat": 0.385,
        "electronegativity": 1.90,
        "abundance": 60,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 30,
        "symbol": "Zn",
        "name": "Zinc",
        "group": "12",
        "period": 4,
        "block": "d-block",
        "atomic_weight": 65.38,
        "density": 7.14,
        "melting_point": 692.88,
        "boiling_point": 1180,
        "specific_heat": 0.388,
        "electronegativity": 1.65,
        "abundance": 70,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 31,
        "symbol": "Ga",
        "name": "Gallium",
        "group": "13",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 69.723,
        "density": 5.91,
        "melting_point": 302.9146,
        "boiling_point": 2673,
        "specific_heat": 0.371,
        "electronegativity": 1.81,
        "abundance": 19,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 32,
        "symbol": "Ge",
        "name": "Germanium",
        "group": "14",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 72.630,
        "density": 5.323,
        "melting_point": 1211.40,
        "boiling_point": 3106,
        "specific_heat": 0.32,
        "electronegativity": 2.01,
        "abundance": 1.5,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 33,
        "symbol": "As",
        "name": "Arsenic",
        "group": "15",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 74.922,
        "density": 5.727,
        "melting_point": 1090,
        "boiling_point": 887,
        "specific_heat": 0.329,
        "electronegativity": 2.18,
        "abundance": 1.8,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 34,
        "symbol": "Se",
        "name": "Selenium",
        "group": "16",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 78.971,
        "density": 4.81,
        "melting_point": 453,
        "boiling_point": 958,
        "specific_heat": 0.321,
        "electronegativity": 2.55,
        "abundance": 0.05,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 35,
        "symbol": "Br",
        "name": "Bromine",
        "group": "17",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 79.904,
        "density": 3.1028,
        "melting_point": 265.8,
        "boiling_point": 332.0,
        "specific_heat": 0.474,
        "electronegativity": 2.96,
        "abundance": 2.4,
        "origin": "primordial",
        "phase": "liquid"
    },
    {
        "atomic_number": 36,
        "symbol": "Kr",
        "name": "Krypton",
        "group": "18",
        "period": 4,
        "block": "p-block",
        "atomic_weight": 83.798,
        "density": 0.003749,
        "melting_point": 115.79,
        "boiling_point": 119.93,
        "specific_heat": 0.248,
        "electronegativity": 3.00,
        "abundance": 1e-4,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 37,
        "symbol": "Rb",
        "name": "Rubidium",
        "group": "1",
        "period": 5,
        "block": "s-block",
        "atomic_weight": 85.468,
        "density": 1.532,
        "melting_point": 312.46,
        "boiling_point": 961,
        "specific_heat": 0.363,
        "electronegativity": 0.82,
        "abundance": 90,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 38,
        "symbol": "Sr",
        "name": "Strontium",
        "group": "2",
        "period": 5,
        "block": "s-block",
        "atomic_weight": 87.62,
        "density": 2.64,
        "melting_point": 1050,
        "boiling_point": 1655,
        "specific_heat": 0.301,
        "electronegativity": 0.95,
        "abundance": 370,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 39,
        "symbol": "Y",
        "name": "Yttrium",
        "group": "3",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 88.906,
        "density": 4.472,
        "melting_point": 1799,
        "boiling_point": 3609,
        "specific_heat": 0.298,
        "electronegativity": 1.22,
        "abundance": 33,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 40,
        "symbol": "Zr",
        "name": "Zirconium",
        "group": "4",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 91.224,
        "density": 6.52,
        "melting_point": 2128,
        "boiling_point": 4682,
        "specific_heat": 0.278,
        "electronegativity": 1.33,
        "abundance": 165,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 41,
        "symbol": "Nb",
        "name": "Niobium",
        "group": "5",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 92.906,
        "density": 8.57,
        "melting_point": 2750,
        "boiling_point": 5017,
        "specific_heat": 0.265,
        "electronegativity": 1.6,
        "abundance": 20,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 42,
        "symbol": "Mo",
        "name": "Molybdenum",
        "group": "6",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 95.95,
        "density": 10.28,
        "melting_point": 2896,
        "boiling_point": 4912,
        "specific_heat": 0.251,
        "electronegativity": 2.16,
        "abundance": 1.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 43,
        "symbol": "Tc",
        "name": "Technetium",
        "group": "7",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 97,
        "density": 11.0,
        "melting_point": 2430,
        "boiling_point": 4538,
        "specific_heat": None,
        "electronegativity": 1.9,
        "abundance": 3e-9,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 44,
        "symbol": "Ru",
        "name": "Ruthenium",
        "group": "8",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 101.07,
        "density": 12.45,
        "melting_point": 2607,
        "boiling_point": 4423,
        "specific_heat": 0.238,
        "electronegativity": 2.2,
        "abundance": 0.001,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 45,
        "symbol": "Rh",
        "name": "Rhodium",
        "group": "9",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 102.91,
        "density": 12.41,
        "melting_point": 2237,
        "boiling_point": 3968,
        "specific_heat": 0.243,
        "electronegativity": 2.28,
        "abundance": 0.001,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 46,
        "symbol": "Pd",
        "name": "Palladium",
        "group": "10",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 106.42,
        "density": 12.023,
        "melting_point": 1828.05,
        "boiling_point": 3236,
        "specific_heat": 0.244,
        "electronegativity": 2.20,
        "abundance": 0.015,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 47,
        "symbol": "Ag",
        "name": "Silver",
        "group": "11",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 107.87,
        "density": 10.49,
        "melting_point": 1234.93,
        "boiling_point": 2435,
        "specific_heat": 0.235,
        "electronegativity": 1.93,
        "abundance": 0.075,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 48,
        "symbol": "Cd",
        "name": "Cadmium",
        "group": "12",
        "period": 5,
        "block": "d-block",
        "atomic_weight": 112.41,
        "density": 8.65,
        "melting_point": 594.22,
        "boiling_point": 1040,
        "specific_heat": 0.232,
        "electronegativity": 1.69,
        "abundance": 0.159,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 49,
        "symbol": "In",
        "name": "Indium",
        "group": "13",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 114.82,
        "density": 7.31,
        "melting_point": 429.75,
        "boiling_point": 2345,
        "specific_heat": 0.233,
        "electronegativity": 1.78,
        "abundance": 0.25,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 50,
        "symbol": "Sn",
        "name": "Tin",
        "group": "14",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 118.71,
        "density": 7.265,
        "melting_point": 505.08,
        "boiling_point": 2875,
        "specific_heat": 0.228,
        "electronegativity": 1.96,
        "abundance": 2.3,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 51,
        "symbol": "Sb",
        "name": "Antimony",
        "group": "15",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 121.76,
        "density": 6.697,
        "melting_point": 903.78,
        "boiling_point": 1860,
        "specific_heat": 0.207,
        "electronegativity": 2.05,
        "abundance": 0.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 52,
        "symbol": "Te",
        "name": "Tellurium",
        "group": "16",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 127.60,
        "density": 6.24,
        "melting_point": 722.66,
        "boiling_point": 1261,
        "specific_heat": 0.202,
        "electronegativity": 2.1,
        "abundance": 0.001,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 53,
        "symbol": "I",
        "name": "Iodine",
        "group": "17",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 126.90,
        "density": 4.933,
        "melting_point": 386.85,
        "boiling_point": 457.4,
        "specific_heat": 0.214,
        "electronegativity": 2.66,
        "abundance": 0.45,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 54,
        "symbol": "Xe",
        "name": "Xenon",
        "group": "18",
        "period": 5,
        "block": "p-block",
        "atomic_weight": 131.29,
        "density": 0.005894,
        "melting_point": 161.4,
        "boiling_point": 165.03,
        "specific_heat": 0.158,
        "electronegativity": 2.60,
        "abundance": 3e-5,
        "origin": "primordial",
        "phase": "gas"
    },
    {
        "atomic_number": 55,
        "symbol": "Cs",
        "name": "Caesium",
        "group": "1",
        "period": 6,
        "block": "s-block",
        "atomic_weight": 132.91,
        "density": 1.93,
        "melting_point": 301.59,
        "boiling_point": 944,
        "specific_heat": 0.242,
        "electronegativity": 0.79,
        "abundance": 3,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 56,
        "symbol": "Ba",
        "name": "Barium",
        "group": "2",
        "period": 6,
        "block": "s-block",
        "atomic_weight": 137.33,
        "density": 3.51,
        "melting_point": 1000,
        "boiling_point": 2170,
        "specific_heat": 0.204,
        "electronegativity": 0.89,
        "abundance": 425,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 57,
        "symbol": "La",
        "name": "Lanthanum",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 138.91,
        "density": 6.162,
        "melting_point": 1193,
        "boiling_point": 3737,
        "specific_heat": 0.195,
        "electronegativity": 1.1,
        "abundance": 39,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 58,
        "symbol": "Ce",
        "name": "Cerium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 140.12,
        "density": 6.770,
        "melting_point": 1068,
        "boiling_point": 3716,
        "specific_heat": 0.192,
        "electronegativity": 1.12,
        "abundance": 66.5,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 59,
        "symbol": "Pr",
        "name": "Praseodymium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 140.91,
        "density": 6.77,
        "melting_point": 1208,
        "boiling_point": 3793,
        "specific_heat": 0.193,
        "electronegativity": 1.13,
        "abundance": 9.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 60,
        "symbol": "Nd",
        "name": "Neodymium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 144.24,
        "density": 7.01,
        "melting_point": 1297,
        "boiling_point": 3347,
        "specific_heat": 0.19,
        "electronegativity": 1.14,
        "abundance": 41.5,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 61,
        "symbol": "Pm",
        "name": "Promethium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 145,
        "density": 7.26,
        "melting_point": 1315,
        "boiling_point": 3273,
        "specific_heat": None,
        "electronegativity": 1.13,
        "abundance": 2e-19,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 62,
        "symbol": "Sm",
        "name": "Samarium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 150.36,
        "density": 7.52,
        "melting_point": 1345,
        "boiling_point": 2067,
        "specific_heat": 0.197,
        "electronegativity": 1.17,
        "abundance": 7.05,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 63,
        "symbol": "Eu",
        "name": "Europium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 151.96,
        "density": 5.244,
        "melting_point": 1099,
        "boiling_point": 1802,
        "specific_heat": 0.182,
        "electronegativity": 1.2,
        "abundance": 2.0,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 64,
        "symbol": "Gd",
        "name": "Gadolinium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 157.25,
        "density": 7.90,
        "melting_point": 1585,
        "boiling_point": 3546,
        "specific_heat": 0.236,
        "electronegativity": 1.2,
        "abundance": 6.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 65,
        "symbol": "Tb",
        "name": "Terbium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 158.93,
        "density": 8.23,
        "melting_point": 1629,
        "boiling_point": 3503,
        "specific_heat": 0.182,
        "electronegativity": 1.2,
        "abundance": 1.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 66,
        "symbol": "Dy",
        "name": "Dysprosium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 162.50,
        "density": 8.540,
        "melting_point": 1680,
        "boiling_point": 2840,
        "specific_heat": 0.17,
        "electronegativity": 1.22,
        "abundance": 5.2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 67,
        "symbol": "Ho",
        "name": "Holmium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 164.93,
        "density": 8.79,
        "melting_point": 1734,
        "boiling_point": 2993,
        "specific_heat": 0.165,
        "electronegativity": 1.23,
        "abundance": 1.3,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 68,
        "symbol": "Er",
        "name": "Erbium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 167.26,
        "density": 9.066,
        "melting_point": 1802,
        "boiling_point": 3141,
        "specific_heat": 0.168,
        "electronegativity": 1.24,
        "abundance": 3.5,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 69,
        "symbol": "Tm",
        "name": "Thulium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 168.93,
        "density": 9.32,
        "melting_point": 1818,
        "boiling_point": 2223,
        "specific_heat": 0.16,
        "electronegativity": 1.25,
        "abundance": 0.52,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 70,
        "symbol": "Yb",
        "name": "Ytterbium",
        "group": "f-block groups",
        "period": 6,
        "block": "f-block",
        "atomic_weight": 173.05,
        "density": 6.90,
        "melting_point": 1097,
        "boiling_point": 1469,
        "specific_heat": 0.155,
        "electronegativity": 1.1,
        "abundance": 3.2,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 71,
        "symbol": "Lu",
        "name": "Lutetium",
        "group": "3",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 174.97,
        "density": 9.841,
        "melting_point": 1925,
        "boiling_point": 3675,
        "specific_heat": 0.154,
        "electronegativity": 1.27,
        "abundance": 0.8,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 72,
        "symbol": "Hf",
        "name": "Hafnium",
        "group": "4",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 178.49,
        "density": 13.31,
        "melting_point": 2506,
        "boiling_point": 4876,
        "specific_heat": 0.144,
        "electronegativity": 1.3,
        "abundance": 3,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 73,
        "symbol": "Ta",
        "name": "Tantalum",
        "group": "5",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 180.95,
        "density": 16.69,
        "melting_point": 3290,
        "boiling_point": 5731,
        "specific_heat": 0.14,
        "electronegativity": 1.5,
        "abundance": 2,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 74,
        "symbol": "W",
        "name": "Tungsten",
        "group": "6",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 183.84,
        "density": 19.25,
        "melting_point": 3695,
        "boiling_point": 6203,
        "specific_heat": 0.132,
        "electronegativity": 2.36,
        "abundance": 1.3,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 75,
        "symbol": "Re",
        "name": "Rhenium",
        "group": "7",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 186.21,
        "density": 21.02,
        "melting_point": 3459,
        "boiling_point": 5869,
        "specific_heat": 0.137,
        "electronegativity": 1.9,
        "abundance": 7e-4,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 76,
        "symbol": "Os",
        "name": "Osmium",
        "group": "8",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 190.23,
        "density": 22.59,
        "melting_point": 3306,
        "boiling_point": 5285,
        "specific_heat": 0.13,
        "electronegativity": 2.2,
        "abundance": 0.002,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 77,
        "symbol": "Ir",
        "name": "Iridium",
        "group": "9",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 192.22,
        "density": 22.56,
        "melting_point": 2719,
        "boiling_point": 4701,
        "specific_heat": 0.131,
        "electronegativity": 2.20,
        "abundance": 0.001,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 78,
        "symbol": "Pt",
        "name": "Platinum",
        "group": "10",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 195.08,
        "density": 21.45,
        "melting_point": 2041.4,
        "boiling_point": 4098,
        "specific_heat": 0.133,
        "electronegativity": 2.28,
        "abundance": 0.005,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 79,
        "symbol": "Au",
        "name": "Gold",
        "group": "11",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 196.97,
        "density": 19.3,
        "melting_point": 1337.33,
        "boiling_point": 3129,
        "specific_heat": 0.129,
        "electronegativity": 2.54,
        "abundance": 0.004,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 80,
        "symbol": "Hg",
        "name": "Mercury",
        "group": "12",
        "period": 6,
        "block": "d-block",
        "atomic_weight": 200.59,
        "density": 13.534,
        "melting_point": 234.43,
        "boiling_point": 629.88,
        "specific_heat": 0.14,
        "electronegativity": 2.00,
        "abundance": 0.085,
        "origin": "primordial",
        "phase": "liquid"
    },
        {
        "atomic_number": 81,
        "symbol": "Tl",
        "name": "Thallium",
        "group": "13",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 204.38,
        "density": 11.85,
        "melting_point": 577,
        "boiling_point": 1746,
        "specific_heat": 0.129,
        "electronegativity": 1.62,
        "abundance": 0.85,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 82,
        "symbol": "Pb",
        "name": "Lead",
        "group": "14",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 207.2,
        "density": 11.34,
        "melting_point": 600.61,
        "boiling_point": 2022,
        "specific_heat": 0.129,
        "electronegativity": 1.87,
        "abundance": 14,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 83,
        "symbol": "Bi",
        "name": "Bismuth",
        "group": "15",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 208.98,
        "density": 9.78,
        "melting_point": 544.7,
        "boiling_point": 1837,
        "specific_heat": 0.122,
        "electronegativity": 2.02,
        "abundance": 0.009,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 84,
        "symbol": "Po",
        "name": "Polonium",
        "group": "16",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 209,
        "density": 9.196,
        "melting_point": 527,
        "boiling_point": 1235,
        "specific_heat": None,
        "electronegativity": 2.0,
        "abundance": 2e-10,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 85,
        "symbol": "At",
        "name": "Astatine",
        "group": "17",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 210,
        "density": 8.91,
        "melting_point": 575,
        "boiling_point": 610,
        "specific_heat": None,
        "electronegativity": 2.2,
        "abundance": 3e-20,
        "origin": "from decay",
        "phase": "unknown"
    },
    {
        "atomic_number": 86,
        "symbol": "Rn",
        "name": "Radon",
        "group": "18",
        "period": 6,
        "block": "p-block",
        "atomic_weight": 222,
        "density": 0.00973,
        "melting_point": 202,
        "boiling_point": 211.3,
        "specific_heat": 0.094,
        "electronegativity": 2.2,
        "abundance": 4e-13,
        "origin": "from decay",
        "phase": "gas"
    },
    {
        "atomic_number": 87,
        "symbol": "Fr",
        "name": "Francium",
        "group": "1",
        "period": 7,
        "block": "s-block",
        "atomic_weight": 223,
        "density": 2.48,
        "melting_point": 281,
        "boiling_point": 890,
        "specific_heat": None,
        "electronegativity": 0.79,
        "abundance": 1e-18,
        "origin": "from decay",
        "phase": "unknown"
    },
    {
        "atomic_number": 88,
        "symbol": "Ra",
        "name": "Radium",
        "group": "2",
        "period": 7,
        "block": "s-block",
        "atomic_weight": 226,
        "density": 5.5,
        "melting_point": 973,
        "boiling_point": 2010,
        "specific_heat": 0.094,
        "electronegativity": 0.9,
        "abundance": 9e-7,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 89,
        "symbol": "Ac",
        "name": "Actinium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 227,
        "density": 10.0,
        "melting_point": 1323,
        "boiling_point": 3471,
        "specific_heat": 0.12,
        "electronegativity": 1.1,
        "abundance": 5.5e-10,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 90,
        "symbol": "Th",
        "name": "Thorium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 232.04,
        "density": 11.7,
        "melting_point": 2115,
        "boiling_point": 5061,
        "specific_heat": 0.113,
        "electronegativity": 1.3,
        "abundance": 9.6,
        "origin": "primordial",
        "phase": "solid"
    },
        {
        "atomic_number": 91,
        "symbol": "Pa",
        "name": "Protactinium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 231.04,
        "density": 15.37,
        "melting_point": 1841,
        "boiling_point": 4300,
        "specific_heat": None,
        "electronegativity": 1.5,
        "abundance": 1.4e-6,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 92,
        "symbol": "U",
        "name": "Uranium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 238.03,
        "density": 19.1,
        "melting_point": 1405.3,
        "boiling_point": 4404,
        "specific_heat": 0.116,
        "electronegativity": 1.38,
        "abundance": 2.7,
        "origin": "primordial",
        "phase": "solid"
    },
    {
        "atomic_number": 93,
        "symbol": "Np",
        "name": "Neptunium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 237,
        "density": 20.45,
        "melting_point": 917,
        "boiling_point": 4273,
        "specific_heat": None,
        "electronegativity": 1.36,
        "abundance": 3e-12,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 94,
        "symbol": "Pu",
        "name": "Plutonium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 244,
        "density": 19.85,
        "melting_point": 912.5,
        "boiling_point": 3501,
        "specific_heat": None,
        "electronegativity": 1.28,
        "abundance": 3e-11,
        "origin": "from decay",
        "phase": "solid"
    },
    {
        "atomic_number": 95,
        "symbol": "Am",
        "name": "Americium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 243,
        "density": 12,
        "melting_point": 1449,
        "boiling_point": 2880,
        "specific_heat": None,
        "electronegativity": 1.13,
        "abundance": None,
        "origin": "synthetic",
        "phase": "solid"
    },
    {
        "atomic_number": 96,
        "symbol": "Cm",
        "name": "Curium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 247,
        "density": 13.51,
        "melting_point": 1613,
        "boiling_point": 3383,
        "specific_heat": None,
        "electronegativity": 1.28,
        "abundance": None,
        "origin": "synthetic",
        "phase": "solid"
    },
    {
        "atomic_number": 97,
        "symbol": "Bk",
        "name": "Berkelium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 247,
        "density": 14.78,
        "melting_point": 1259,
        "boiling_point": 2900,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "solid"
    },
    {
        "atomic_number": 98,
        "symbol": "Cf",
        "name": "Californium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 251,
        "density": 15.1,
        "melting_point": 1173,
        "boiling_point": 1743,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "solid"
    },
    {
        "atomic_number": 99,
        "symbol": "Es",
        "name": "Einsteinium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 252,
        "density": 8.84,
        "melting_point": 1133,
        "boiling_point": 1269,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "solid"
    },
    {
        "atomic_number": 100,
        "symbol": "Fm",
        "name": "Fermium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 257,
        "density": 9.7,
        "melting_point": 1125,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
        {
        "atomic_number": 101,
        "symbol": "Md",
        "name": "Mendelevium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 258,
        "density": 10.3,
        "melting_point": 1100,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 102,
        "symbol": "No",
        "name": "Nobelium",
        "group": "f-block groups",
        "period": 7,
        "block": "f-block",
        "atomic_weight": 259,
        "density": 9.9,
        "melting_point": 1100,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 103,
        "symbol": "Lr",
        "name": "Lawrencium",
        "group": "3",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 266,
        "density": 14.4,
        "melting_point": 1900,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": 1.3,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 104,
        "symbol": "Rf",
        "name": "Rutherfordium",
        "group": "4",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 267,
        "density": 17,
        "melting_point": 2400,
        "boiling_point": 5800,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 105,
        "symbol": "Db",
        "name": "Dubnium",
        "group": "5",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 268,
        "density": 21.6,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 106,
        "symbol": "Sg",
        "name": "Seaborgium",
        "group": "6",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 269,
        "density": 23.5,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 107,
        "symbol": "Bh",
        "name": "Bohrium",
        "group": "7",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 270,
        "density": 26.5,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 108,
        "symbol": "Hs",
        "name": "Hassium",
        "group": "8",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 269,
        "density": 28,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 109,
        "symbol": "Mt",
        "name": "Meitnerium",
        "group": "9",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 278,
        "density": 27.5,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 110,
        "symbol": "Ds",
        "name": "Darmstadtium",
        "group": "10",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 281,
        "density": 26.5,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
        {
        "atomic_number": 111,
        "symbol": "Rg",
        "name": "Roentgenium",
        "group": "11",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 282,
        "density": 23,
        "melting_point": None,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 112,
        "symbol": "Cn",
        "name": "Copernicium",
        "group": "12",
        "period": 7,
        "block": "d-block",
        "atomic_weight": 285,
        "density": 14.0,
        "melting_point": 283,
        "boiling_point": 340,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 113,
        "symbol": "Nh",
        "name": "Nihonium",
        "group": "13",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 286,
        "density": 16,
        "melting_point": 700,
        "boiling_point": 1400,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 114,
        "symbol": "Fl",
        "name": "Flerovium",
        "group": "14",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 289,
        "density": 11.4,
        "melting_point": 284,
        "boiling_point": None,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 115,
        "symbol": "Mc",
        "name": "Moscovium",
        "group": "15",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 290,
        "density": 13.5,
        "melting_point": 700,
        "boiling_point": 1400,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 116,
        "symbol": "Lv",
        "name": "Livermorium",
        "group": "16",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 293,
        "density": 12.9,
        "melting_point": 700,
        "boiling_point": 1100,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 117,
        "symbol": "Ts",
        "name": "Tennessine",
        "group": "17",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 294,
        "density": 7.2,
        "melting_point": 700,
        "boiling_point": 883,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    },
    {
        "atomic_number": 118,
        "symbol": "Og",
        "name": "Oganesson",
        "group": "18",
        "period": 7,
        "block": "p-block",
        "atomic_weight": 294,
        "density": 7,
        "melting_point": 325,
        "boiling_point": 450,
        "specific_heat": None,
        "electronegativity": None,
        "abundance": None,
        "origin": "synthetic",
        "phase": "unknown"
    }
]